// <auto-generated />
using System;
using Demo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200717161812_AddEmailToStudentTable")]
    partial class AddEmailToStudentTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Demo.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            Name = "C0120"
                        },
                        new
                        {
                            ClassId = 2,
                            Name = "C0220"
                        },
                        new
                        {
                            ClassId = 3,
                            Name = "C0320"
                        });
                });

            modelBuilder.Entity("Demo.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            ClassId = 1,
                            Dob = new DateTime(1990, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "xuantrung@email.com",
                            FullName = "Trung",
                            Gender = 0
                        },
                        new
                        {
                            StudentId = 2,
                            ClassId = 1,
                            Dob = new DateTime(1991, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quang@email.com",
                            FullName = "Quang",
                            Gender = 0
                        },
                        new
                        {
                            StudentId = 3,
                            ClassId = 1,
                            Dob = new DateTime(1992, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "minh@email.com",
                            FullName = "Minh",
                            Gender = 0
                        },
                        new
                        {
                            StudentId = 4,
                            ClassId = 2,
                            Dob = new DateTime(1993, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tram@email.com",
                            FullName = "Trâm",
                            Gender = 1
                        },
                        new
                        {
                            StudentId = 5,
                            ClassId = 2,
                            Dob = new DateTime(1994, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ghi@email.com",
                            FullName = "Ghi",
                            Gender = 1
                        });
                });

            modelBuilder.Entity("Demo.Models.Student", b =>
                {
                    b.HasOne("Demo.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
